### ISSUE TITLE
have new clients behave more aggressively for a time period.

### ISSUE THREAD

**Issue by jgstew** [strawgate/C3-Platform-Kickstart#3]
It would be useful if there was an easy / pre packaged way to get all new clients to behave more aggressively, but then have them scale back to normal behavior after a certain time period to speed up provisioning. 

Ideally the client would be installed with a clientsettings.cfg to speed it up, but if not, then ideally an action would set the same settings if not already there, then another action would scale it back after a delay.

**Comment by strawgate** [comment]
Agreed!

What are your thoughts on timeliness and aggressiveness?

maybe 3 sets?
25% CPU for 1 day and then default CPU after that
10% CPU for 1 day and then default CPU after that
5% CPU for 1 day and then default CPU after that

**Comment by jgstew** [comment]
I go back and forth about timeliness and aggressiveness.

Could do something like ~25% for 4 hours, ~10% for 20 hours, ~5% for ??

**Comment by strawgate** [comment]
Fixed by 4f04a6d3f89ed8ae881e3d5f7d2922d6a8099416
